name: LogItAll
description: "A Personal Utility app for Myself."
publish_to: 'none'

version: 1.0.1+1 

environment:
  sdk: '>=3.2.3 <4.0.0'  # Updated to the latest stable Dart SDK constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # Already the latest version, no change needed
  shared_preferences: ^2.0.6 # Ensure this line is present and correct
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  csv: ^5.1.1
  excel: ^4.0.2
  sqflite: ^2.3.0
  intl: ^0.19.0
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Upgraded to the latest major version (from 3.0.1)

flutter:
  uses-material-design: true

dependency_overrides:
  characters: ^1.4.0
  collection: ^1.19.1
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  async: ^2.12.0
  boolean_selector: ^2.1.2
  clock: ^1.1.2
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  matcher: ^0.12.17
  path: ^1.9.1
  source_span: ^1.10.1
  stack_trace: ^1.12.1
  stream_channel: ^2.1.4
  string_scanner: ^1.4.1
  term_glyph: ^1.2.2
  test_api: ^0.7.4
  vm_service: ^15.0.0